import json
import os

dict_path = r'c:\Users\Rakua\Documents\VScode\Java script\ブラウザ拡張機能\Github_translate_Japanease\data\dictionary.json'

new_entries = {
    # Countries & Regions (Extensive list from logs)
    "Nepal": "ネパール",
    "Nauru": "ナウル",
    "Namibia": "ナミビア",
    "Myanmar": "ミャンマー",
    "Mozambique": "モザンビーク",
    "Morocco": "モロッコ",
    "Montserrat": "モンセラート",
    "Montenegro": "モンテネグロ",
    "Mongolia": "モンゴル",
    "Monaco": "モナコ",
    "Moldova": "モルドバ",
    "Micronesia": "ミクロネシア",
    "Mayotte": "マヨット",
    "Mauritius": "モーリシャス",
    "Mauritania": "モーリタニア",
    "Martinique": "マルティニーク",
    "Marshall Islands": "マーシャル諸島",
    "Malta": "マルタ",
    "Mali": "マリ",
    "Maldives": "モルディブ",
    "Malawi": "マラウイ",
    "Madagascar": "マダガスカル",
    "Macedonia": "北マケドニア",
    "Macau": "マカオ",
    "Lithuania": "リトアニア",
    "Liechtenstein": "リヒテンシュタイン",
    "Libya": "リビア",
    "Liberia": "リベリア",
    "Lesotho": "レソト",
    "Lebanon": "レバノン",
    "Latvia": "ラトビア",
    "Laos": "ラオス",
    "Kyrgyzstan": "キルギス",
    "Kuwait": "クウェート",
    "Korea, South": "韓国",
    "Kiribati": "キリバス",
    "Kenya": "ケニア",
    "Kazakhstan": "カザフスタン",
    "Jordan": "ヨルダン",
    "Jersey": "ジャージー",
    "Jamaica": "ジャマイカ",
    "Isle of Man": "マン島",
    "Iraq": "イラク",
    "Iran": "イラン",
    "Honduras": "ホンジュラス",
    "Heard and McDonald Islands": "ハード島とマクドナルド諸島",
    "Haiti": "ハイチ",
    "Guyana": "ガイアナ",
    "Guinea-Bissau": "ギニアビサウ",
    "Guinea": "ギニア",
    "Guernsey": "ガーンジー",
    "Guatemala": "グアテマラ",
    "Guam": "グアム",
    "Guadeloupe": "グアドループ",
    "Grenada": "グレナダ",
    "Greenland": "グリーンランド",
    "Gibraltar": "ジブラルタル",
    "Ghana": "ガーナ",
    "Gambia": "ガンビア",
    "Gabon": "ガボン",
    "French Southern Lands": "フランス領南方・南極地域",
    "French Polynesia": "フランス領ポリネシア",
    "French Guiana": "フランス領ギアナ",
    "Fiji": "フィジー",
    "Faroe Islands": "フェロー諸島",
    "Falkland Islands": "フォークランド諸島",
    "Ethiopia": "エチオピア",
    "Estonia": "エストニア",
    "Eritrea": "エリトリア",
    "Equatorial Guinea": "赤道ギニア",
    "El Salvador": "エルサルバドル",
    "Ecuador": "エクアドル",
    "Dominican Republic": "ドミニカ共和国",
    "Dominica": "ドミニカ国",
    "Djibouti": "ジブチ",
    "Curaçao": "キュラソー",
    "Côte d'Ivoire": "コートジボワール",
    "Cook Islands": "クック諸島",
    "Congo (Kinshasa)": "コンゴ民主共和国",
    "Congo (Brazzaville)": "コンゴ共和国",
    "Comoros": "コモロ",
    "Cocos (Keeling) Islands": "ココス（キーリング）諸島",
    "Christmas Island": "クリスマス島",
    "Chad": "チャド",
    "Central African Republic": "中央アフリカ共和国",
    "Cayman Islands": "ケイマン諸島",
    "Cape Verde": "カーボベルデ",
    "Cameroon": "カメルーン",
    "Cambodia": "カンボジア",
    "Burundi": "ブルンジ",
    "Burkina Faso": "ブルキナファソ",
    "Brunei Darussalam": "ブルネイ",
    "British Indian Ocean Territory": "イギリス領インド洋地域",
    "Bouvet Island": "ブーベ島",
    "Bonaire, Sint Eustatius and Saba": "ボネール、シント・ユースタティウスおよびサバ",
    "Aruba": "アルバ",
    "Armenia": "アルメニア",
    "Argentina": "アルゼンチン",
    "Antigua and Barbuda": "アンティグア・バーブーダ",
    "Åland": "オーランド諸島",
    "Afghanistan": "アフガニスタン",
}

with open(dict_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

for k, v in new_entries.items():
    if k not in data:
        data[k] = v

with open(dict_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Dictionary updated with {len(new_entries)} items for v1.1.19.")
